# This is a basic workflow to help you get started with Actions

name: Schemathesis_local_install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains deployment jobs"
  Local-Install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out repo content
        uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v4
        #with:
        #  python-version: 3.10 # install the python needed
          
      - name: Schemathesis
        run: |
          python -m pip install --upgrade pip
          pip install schemathesis
          schemathesis run --report --hypothesis-max-examples=5 https://api.swaggerhub.com/apis/PEBELTON_1/trial/1.0.1/swagger.json
      
