# This is a basic workflow to help you get started with Actions

name: Schemathesis_local_install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains deployment jobs"
  Local-Install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out repo content
        uses: actions/checkout@v2
        
     
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # install the python needed

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip

      - name: Schemathesis
        run: |
          python -m pip install --upgrade pip
          pip install httpx
          pip install schemathesis
          schemathesis run --checks all --junit-xml=results.xml https://api.swaggerhub.com/apis/PEBELTON_1/trial/1.0.2/swagger.json > runOutput.txt

      - name: Attach report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Schemathesis.xml
          path: results.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.5.0
        if: always()
        with:
         report_paths: 'results.xml'
         check_name: 'Schemathesis Test Report'
         include_passed: 'true'
         require_tests: 'true'
         
      - name: Extract Summary
        if: always()
        run: |
          sudo chmod 701 .github/scripts/extractSummary.sh
          .github/scripts/extractSummary.sh
        shell: bash
        
      - name: Attach report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Summary.txt
          path: summary.txt
     
